"""fixed student column

Revision ID: 015eb1b6357b
Revises: 3bc3cfbe36e1
Create Date: 2025-03-28 12:26:20.180207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015eb1b6357b'
down_revision: Union[str, None] = '3bc3cfbe36e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('student_course', sa.String(length=100), nullable=False))
    op.drop_column('bookings', 'Student_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('Student_course', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'student_course')
    # ### end Alembic commands ###
