
"""added occupancy to rooms model

Revision ID: 0dd628af774d
Revises: 015eb1b6357b
Create Date: 2025-03-28 14:38:26.922471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd628af774d'
down_revision: Union[str, None] = '015eb1b6357b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('occupancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'occupancy')
    # ### end Alembic commands ###
