"""created document table

Revision ID: 369f11b9be1e
Revises: b5c5fc5129c9
Create Date: 2025-04-02 15:47:08.391173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369f11b9be1e'
down_revision: Union[str, None] = 'b5c5fc5129c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('minio_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=True),
    sa.Column('object_name', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.String(length=50), nullable=True),
    sa.Column('etag', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('rooms', 'booked_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'booked_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('pdf_documents')
    # ### end Alembic commands ###
