""" created users tables

Revision ID: 3bc3cfbe36e1
Revises: 
Create Date: 2025-03-28 11:12:59.267936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc3cfbe36e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('student_phone', sa.String(length=20), nullable=False),
    sa.Column('student_university', sa.String(length=100), nullable=False),
    sa.Column('Student_course', sa.String(length=100), nullable=False),
    sa.Column('student_study_year', sa.String(length=50), nullable=False),
    sa.Column('home_address', sa.String(length=100), nullable=False),
    sa.Column('home_district', sa.String(length=100), nullable=False),
    sa.Column('home_country', sa.String(length=50), nullable=False),
    sa.Column('next_of_kin_name', sa.String(length=100), nullable=False),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=False),
    sa.Column('kin_relationship', sa.String(length=50), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_student_email'), 'bookings', ['student_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_student_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
