"""dropping a column

Revision ID: 529bd0887b79
Revises: b4abf3f74eb7
Create Date: 2025-03-25 14:33:31.935647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529bd0887b79'
down_revision: Union[str, None] = 'b4abf3f74eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostels', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
