"""remodeling image metadata table

Revision ID: 67ccd2a2f499
Revises: a4279bb36db6
Create Date: 2025-05-24 15:15:05.307806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67ccd2a2f499'
down_revision: Union[str, None] = 'a4279bb36db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('draft_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_images_draft_id'), 'images', ['draft_id'], unique=False)
    op.drop_column('images', 'image_type')
    op.drop_column('images', 'is_primary')
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('image_type', postgresql.ENUM('HOSTEL', 'ROOM', name='imagetype'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_images_draft_id'), table_name='images')
    op.drop_column('images', 'draft_id')
    # ### end Alembic commands ###
