"""droppping unique constraint on booking emails

Revision ID: a13d009e7fe8
Revises: 0dd628af774d
Create Date: 2025-03-28 14:58:30.595709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13d009e7fe8'
down_revision: Union[str, None] = '0dd628af774d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_student_email', table_name='bookings')
    op.create_index(op.f('ix_bookings_student_email'), 'bookings', ['student_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_student_email'), table_name='bookings')
    op.create_index('ix_bookings_student_email', 'bookings', ['student_email'], unique=True)
    # ### end Alembic commands ###
