"""updating user tables

Revision ID: af57615732a6
Revises: 982d10f4b90a
Create Date: 2025-03-22 10:52:58.207173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af57615732a6'
down_revision: Union[str, None] = '982d10f4b90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_owners', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('hostel_owners_id_fkey', 'hostel_owners', type_='foreignkey')
    op.create_foreign_key(None, 'hostel_owners', 'users', ['user_id'], ['id'])
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('students_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_id_fkey', 'students', 'users', ['id'], ['id'])
    op.drop_column('students', 'user_id')
    op.drop_constraint(None, 'hostel_owners', type_='foreignkey')
    op.create_foreign_key('hostel_owners_id_fkey', 'hostel_owners', 'users', ['id'], ['id'])
    op.drop_column('hostel_owners', 'user_id')
    # ### end Alembic commands ###
