"""added image url to hostels

Revision ID: b4abf3f74eb7
Revises: 91b2277b69ec
Create Date: 2025-03-25 13:11:55.566347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4abf3f74eb7'
down_revision: Union[str, None] = '91b2277b69ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('hostels', sa.Column('average_price', sa.Integer(), nullable=False))
    op.drop_column('hostels', 'price_per_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('price_per_month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hostels', 'average_price')
    op.drop_column('hostels', 'image_url')
    # ### end Alembic commands ###
