"""added rules and regulations column

Revision ID: d1c2c7d064e1
Revises: a13d009e7fe8
Create Date: 2025-03-31 15:10:19.176916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c2c7d064e1'
down_revision: Union[str, None] = 'a13d009e7fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('rules_and_regulations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'rules_and_regulations')
    # ### end Alembic commands ###
