"""created images and receipt tables

Revision ID: f65ff797fb3b
Revises: fa78199825b9
Create Date: 2025-04-02 08:57:53.491112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65ff797fb3b'
down_revision: Union[str, None] = 'fa78199825b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='receiptstatus'), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('bucket_name', sa.String(length=50), nullable=True),
    sa.Column('object_name', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.String(length=50), nullable=True),
    sa.Column('etag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('image_type', sa.Enum('HOSTEL', 'ROOM', name='imagetype'), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('bucket_name', sa.String(length=50), nullable=True),
    sa.Column('object_name', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.String(length=50), nullable=True),
    sa.Column('etag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
