"""Fixed rules and regulations column to hostels tables

Revision ID: fa78199825b9
Revises: d1c2c7d064e1
Create Date: 2025-03-31 15:44:53.645374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa78199825b9'
down_revision: Union[str, None] = 'd1c2c7d064e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('rules_and_regulations', sa.Text(), nullable=True))
    op.drop_column('rooms', 'rules_and_regulations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('rules_and_regulations', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('hostels', 'rules_and_regulations')
    # ### end Alembic commands ###
